# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: '$(Build.SourcesDirectory)\bin\hugo.exe -s $(Build.SourcesDirectory)\blog -d 

- task: AzureFileCopy@5
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)'
    azureSubscription: 'Solve Solutions (e9cd9f74-e762-4755-a2db-7f02bf990173)'
    Destination: 'AzureBlob'
    storage: 'mckproductionblog'
    ContainerName: '$web' --log -v'
    displayName: 'Build site'