baseURL = "https://michael-mckenna.com"
locale = "en-US"
title = "Michael McKenna"
themesDir = "themes"
theme = "win95"
enableGitInfo = true
defaultContentLanguage = "en"
disableKinds = ["term", "taxonomy"]

[permalinks]
  post = "/blog/:slug/"
  note = "/notes/:slug/"
  activity = "/activity/:year/:month/:slug/"
  project = "/projects/:slug/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = 'github-dark'
    tabWidth = 4
  [markup.goldmark.extensions]
    footnote = true
  [markup.goldmark.renderer]
    hardWraps = true

[Params.Win95]
    favicon = "favicon.png"
    subtitle = "All my Keystrokes That's Fit to Print"

[Params.IndieWeb]
    name = "Michael McKenna"
    url = "https://michael-mckenna.com/"
    photo = "/images/site/45eb93e3-6a59-4a2e-a16a-4dbfafc1a531.jpg"
    note = "A study in imperfection; a collection of the intangible."
    authorizationEndpoint = "https://talos.michael-mckenna.com/auth"
    tokenEndpoint = "https://talos.michael-mckenna.com/token"
    metadataEndpoint = "https://talos.michael-mckenna.com/.well-known/oauth-authorization-server"
    webmentionEndpoint = "https://lilpub.michael-mckenna.com/webmention"

[[Params.IndieWeb.identities]]
    name = "GitHub"
    url = "https://github.com/myquay"
    authentication = true

[outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "rss"

[outputFormats.WINDOW]
    mediaType = "text/html"
    baseName = "window"
    isHTML = true
    notAlternative = true

[outputs]
    home = ["HTML", "RSS", "WINDOW"]
    section = ["HTML", "RSS", "WINDOW"]
    page = ["HTML", "WINDOW"]
