baseURL = "https://michael-mckenna.com"
languageCode = "en-us"
title = "Michael McKenna"
themesDir = "themes"
theme = "hugo-theme-peripheral"
googleAnalytics = "UA-27845504-8"
enableGitInfo = true

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params.Peripheral]
    subtitle = "All my Keystrokes That's Fit to Print"
    location = "Auckland, New Zealand"
    github = "myquay"
    
[Params]
  homeTitle = "Hi, I'm Michael"
  subtitle = "Software and Startups"
  favicon = "favicon.png"
  dateFormat = "January 2, 2006"
  rss = true
  showFragments = true

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/myquay"
    github   = "https://www.github.com/myquay"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 2

[[menu.main]]
    name = "Fragments"
    url = "/fragments"
    weight = 3

[[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 5

[Author]
	name = "Michael McKenna"
	website = "https://michael-mckenna.com"